### ISSUE TITLE
Create Item Example

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net-examples#3]
Hi,

Can you add code to CRUD items? I am trying to add a default price. Also, how do I associate accounts?

`            ItemCreate create = new ItemCreate()
            {
                ItemName = detail.Name,
                ItemId = detail.Sku,
                CogsGlAccountNo = settings.ItemCOGSAcct,
                InventoryGlAccountNo = settings.ItemAssetAcct,
                RevenueGlAccountNo = settings.ItemIncomeAcct,
                ItemType = detail.Product.IsInventory ? "Inventory" : null,
                SalesDescription = detail.Product.Description,
                PurchasingDescription = detail.Product.Description,
                BasePrice = detail.PriceExclTax,
                Active = true,
            };

            Task<OnlineResponse> createTask = Client().Execute(create);
            createTask.Wait();
`

`<?xml version="1.0" encoding="UTF-8"?><response><control><status>success</status><senderid>A</senderid><controlid>1517939211.19031</controlid><uniqueid>false</uniqueid><dtdversion>3.0</dtdversion></control><operation><authentication><status>success</status><userid>A</userid><companyid>A-DEV</companyid><sessiontimestamp>2018-02-06T09:46:50-08:00</sessiontimestamp></authentication><result><status>failure</status><function>create</function><controlid>12cee643-0b0d-4cc2-9047-8ea002429361</controlid><data listtype="objects" count="0"/><errormessage><error><errorno>BL01001973</errorno><description></description><description2>Could not create invpricelistentry record!</description2><correction></correction></error><error><errorno>BL01001973</errorno><description></description><description2>Could not create invpricelistentrymanager record!</description2><correction></correction></error><error><errorno>BL01001973</errorno><description></description><description2>Error update Price List base</description2><correction></correction></error><error><errorno>BL01001973</errorno><description></description><description2>Could not create Item record!</description2><correction></correction></error></errormessage></result></operation></response>`

**Comment by jimmymcpeter** [comment]
If you're changing the example code to try the item object, and it's an actual bug with the SDK (not the Intacct API itself), you should really open it as an [issue on the SDK repo](https://github.com/Intacct/intacct-sdk-net/issues).  It's likely something with the request XML you are sending which I recommend providing, not just the object with a bunch of variables - I don't know what your variables are set to.
